from datetime import datetime
import io


def _sanitize(text: str) -> str:
    """Replace Unicode chars that latin-1 built-in fonts can't render."""
    return (
        text
        .replace("\u2013", "-")   # en-dash
        .replace("\u2014", "-")   # em-dash
        .replace("\u2018", "'")   # left single quote
        .replace("\u2019", "'")   # right single quote
        .replace("\u201c", '"')   # left double quote
        .replace("\u201d", '"')   # right double quote
        .replace("\u2265", ">=")  # ≥
        .replace("\u2264", "<=")  # ≤
        .replace("\u00b0", " ")   # degree sign
        .replace("\u2022", "-")   # bullet
        .replace("\u2192", "->")  # →
        .replace("\u00b7", "-")   # middle dot
        .encode("latin-1", errors="replace").decode("latin-1")
    )


def _hb_from_pcv(pcv):
    return round(pcv / 3, 1)


def _build_sections(input_data: dict, result: dict) -> list:
    """Build a list of (heading, lines) tuples for the report."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    risk = result.get("risk_level", "N/A")
    pcv = input_data.get("pcv", 0)
    hb = _hb_from_pcv(pcv)

    fbc_lines = []
    if input_data.get("wbc"):
        fbc_lines.append(f"WBC: {input_data['wbc']} x10^3/uL")
    if input_data.get("neutrophils"):
        fbc_lines.append(f"Neutrophils: {input_data['neutrophils']}%")
    if input_data.get("platelets"):
        fbc_lines.append(f"Platelets: {input_data['platelets']} x10^3/uL")

    sections = [
        ("MAMACORD AI TRIAGE REPORT", [
            f"Generated: {ts}",
            f"Risk Level: {risk}",
        ]),
        ("PATIENT DETAILS", [
            f"Patient ID: {input_data.get('patient_id') or 'N/A'}",
            f"Age: {input_data.get('age')} years",
            f"Gestational Age: {input_data.get('gestational_age')} weeks",
            f"Gravida: {input_data.get('gravida') or 'N/A'}  |  Para: {input_data.get('para') or 'N/A'}",
        ]),
        ("VITAL SIGNS", [
            f"Blood Pressure: {input_data.get('systolic_bp')}/{input_data.get('diastolic_bp')} mmHg",
            f"Temperature: {input_data.get('temperature')} C",
            f"Heart Rate: {input_data.get('heart_rate')} bpm",
        ]),
        ("POINT-OF-CARE TESTS", [
            f"PCV: {pcv}%  (est. Hb: {hb} g/dL)",
            f"Urine Protein: {input_data.get('urine_protein', 'N/A')}",
            f"Urine Glucose: {input_data.get('urine_glucose', 'N/A')}",
        ] + (fbc_lines if fbc_lines else [])),
        ("USS FINDINGS", [
            f"Placental Location: {input_data.get('placental_location') or 'Not assessed'}",
            f"Fetal Presentation: {input_data.get('fetal_presentation') or 'Not assessed'}",
            f"Liquor Volume: {input_data.get('liquor_volume') or 'Not assessed'}",
            f"FHR: {input_data.get('fhr') or 'Not assessed'} bpm",
        ]),
        ("ASSESSMENT", [
            f"Primary Concern: {result.get('primary_concern', '')}",
            f"Recommended Action: {result.get('recommended_action', '')}",
        ]),
        ("CLINICAL FLAGS", result.get("flags", [])),
        ("CLINICAL RATIONALE", [result.get("rationale", "")]),
        ("GUIDELINE CITATIONS", result.get("citations", [])),
        ("DISCLAIMER", [
            "Generated by Mamacord AI | Nigerian National Maternal Health Guidelines + WHO Protocols",
            "This report is a clinical decision support tool and does not replace qualified medical judgement.",
        ]),
    ]
    return sections


def generate_pdf(input_data: dict, result: dict) -> bytes:
    from fpdf import FPDF

    sections = _build_sections(input_data, result)
    risk = result.get("risk_level", "N/A")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    # Risk colour banner
    colour_map = {"RED": (200, 30, 30), "YELLOW": (220, 168, 0), "GREEN": (22, 160, 80)}
    r, g, b = colour_map.get(risk, (100, 100, 100))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "MAMACORD AI TRIAGE REPORT", new_x="LMARGIN", new_y="NEXT", align="C", fill=True)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, _sanitize(f"Risk Level: {risk}"), new_x="LMARGIN", new_y="NEXT", align="C", fill=True)
    pdf.ln(4)

    pdf.set_text_color(0, 0, 0)

    for heading, lines in sections[1:]:  # skip first section already rendered
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 7, _sanitize(heading), new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.set_font("Helvetica", "", 9)
        for line in lines:
            if line:
                # wrap long lines
                pdf.multi_cell(0, 6, _sanitize(f"  {line}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    return bytes(pdf.output())


def generate_docx(input_data: dict, result: dict) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    sections = _build_sections(input_data, result)
    risk = result.get("risk_level", "N/A")

    doc = Document()

    colour_map = {"RED": RGBColor(0xC8, 0x1E, 0x1E), "YELLOW": RGBColor(0xDC, 0xA8, 0x00), "GREEN": RGBColor(0x16, 0xA0, 0x50)}
    risk_colour = colour_map.get(risk, RGBColor(0x33, 0x33, 0x33))

    # Title
    title = doc.add_heading("MAMACORD AI TRIAGE REPORT", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x8B, 0x1A, 0x1A)

    risk_para = doc.add_paragraph()
    risk_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = risk_para.add_run(f"Risk Level: {risk}")
    run.bold = True
    run.font.size = Pt(14)
    run.font.color.rgb = risk_colour

    doc.add_paragraph()

    for heading, lines in sections[1:]:
        h = doc.add_heading(heading, level=2)
        for r in h.runs:
            r.font.color.rgb = RGBColor(0x8B, 0x1A, 0x1A)
        for line in lines:
            if line:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(line).font.size = Pt(10)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
